/**
 * 📖 Textual Wiki Archive Generator for GitHub Repositories
 * Generates clean, image-free, highly structured Markdown/Text Wiki documentation
 * with direct clickable URLs, classified from A to Z, ranked by Strategic Impact.
 */

import { GitHubRepoItem } from "./repo_indexer";

export class WikiGenerator {
  public generateWikiMarkdown(catalog: GitHubRepoItem[]): string {
    const sorted = [...catalog].sort((a, b) => a.name.localeCompare(b.name));

    let md = `# 📖 Universal GitHub Intelligence Wiki Archive\n`;
    md += `*Generated by GitHub Agent Studio — Comprehensive A-to-Z Repository & Forkability Index*\n\n`;
    md += `---\n\n`;

    // 1. High Priority Summary
    const immediate = sorted.filter(r => r.scoreCard.totalScore >= 88);
    md += `## 🚀 Tier 1: Immediate Study & High-Impact Fork Targets (Score ≥ 88/100)\n\n`;
    immediate.forEach(r => {
      md += `* **[${r.name}](${r.url})** (\`${r.fullName}\`) — **Score: ${r.scoreCard.totalScore}/100** [${r.scoreCard.recommendation}]\n`;
      md += `  * **Author/Owner:** \`${r.owner}\` | **Language:** ${r.language} | **Stars:** ★ ${r.stars.toLocaleString()} | **Forks:** ⑂ ${r.forks.toLocaleString()}\n`;
      md += `  * **Description:** ${r.description}\n`;
      md += `  * **Strategic Rationale:** ${r.scoreCard.strategicRationale}\n`;
      md += `  * **Enhancement Vectors:** ${r.scoreCard.suggestedEnhancementRoadmap.slice(0, 2).join(" • ")}\n\n`;
    });

    md += `---\n\n`;

    // 2. Full A-to-Z Alphabetical Index
    md += `## 🔤 Complete A-to-Z Repository Catalog\n\n`;

    const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
    for (const letter of letters) {
      const itemsForLetter = sorted.filter(r => r.name.toUpperCase().startsWith(letter));
      if (itemsForLetter.length > 0) {
        md += `### ${letter}\n\n`;
        itemsForLetter.forEach(r => {
          md += `* **[${r.name}](${r.url})** by [\`${r.owner}\`](https://github.com/${r.owner})\n`;
          md += `  * **Category:** \`${r.category}\` | **Language:** ${r.language} | **Score:** \`${r.scoreCard.totalScore}/100\` (${r.scoreCard.recommendation})\n`;
          md += `  * **Stars:** ★ ${r.stars.toLocaleString()} | **Forks:** ⑂ ${r.forks.toLocaleString()}\n`;
          md += `  * **Summary:** ${r.description}\n\n`;
        });
      }
    }

    md += `---\n\n`;
    md += `*Total Repositories Indexed: ${catalog.length} | Generated on: ${new Date().toISOString().split("T")[0]}*\n`;

    return md;
  }
}
